; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "WithCrypt"
!define PRODUCT_VERSION "0.2.0"
!define PRODUCT_PUBLISHER "TeamAST"
!define PRODUCT_WEB_SITE "http://github.com/teamast"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\withcrypt.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; Target architecture: makensis /DARCH=x64|x86|arm64 Installer.nsi (default x64).
; Binaries come from scripts\build-windows.ps1 -Architecture <arch>.
!ifndef ARCH
  !define ARCH "x64"
!endif
!if "${ARCH}" == "x64"
  !define RUST_TARGET "x86_64-pc-windows-msvc"
!else if "${ARCH}" == "x86"
  !define RUST_TARGET "i686-pc-windows-msvc"
!else if "${ARCH}" == "arm64"
  !define RUST_TARGET "aarch64-pc-windows-msvc"
!else
  !error "ARCH must be x64, x86 or arm64"
!endif
!define SOURCE_DIR "..\target\${RUST_TARGET}\release"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include LogicLib.nsh
!include WinVer.nsh
!include x64.nsh

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
!insertmacro MUI_PAGE_LICENSE "..\LICENSE"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\withcrypt-gui.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "WithCrypt-setup-${ARCH}.exe"
!if "${ARCH}" == "x86"
  InstallDir "$PROGRAMFILES\WithCrypt"
!else
  InstallDir "$PROGRAMFILES64\WithCrypt"
!endif
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
BrandingText "WithCrypt Install Engine"

Section "Main Program" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "${SOURCE_DIR}\withcrypt.exe"
  File "${SOURCE_DIR}\ShellIcon.ico"
  File "${SOURCE_DIR}\withcrypt-gui.exe"
  File "${SOURCE_DIR}\withcrypt-setup.exe"
  File "${SOURCE_DIR}\withcrypt_shell.dll"
!if "${ARCH}" != "x86"
  File "${SOURCE_DIR}\WithCrypt.Shell.msix"
!endif
  
  CreateDirectory "$SMPROGRAMS\WithCrypt"
  CreateShortCut "$SMPROGRAMS\WithCrypt\WithCrypt.lnk" "$INSTDIR\withcrypt-gui.exe"
  CreateShortCut "$DESKTOP\WithCrypt.lnk" "$INSTDIR\withcrypt-gui.exe"
  
  DetailPrint "Detecting Windows Version ..."
  ${WinVerGetBuild} $0
  ${If} $0 >= 22000
    DetailPrint "Windows 11 detected (Build: $0)"
    DetailPrint "Registering shell extension ..."
    nsExec::ExecToLog "$INSTDIR\withcrypt-setup.exe register"
  ${Else}
    DetailPrint "Windows 10 or older detected (Build: $0)"
    DetailPrint "Registering shell extension ..."
    nsExec::ExecToLog "$INSTDIR\withcrypt-setup.exe register --classic-only"
  ${EndIf}
  
SectionEnd

Function .onInit
!if "${ARCH}" == "x64"
  ${IfNot} ${IsNativeAMD64}
    MessageBox MB_ICONSTOP|MB_OK "This installer is for x64 Windows. Use the ARM64 or x86 installer."
    Abort
  ${EndIf}
  SetRegView 64
!else if "${ARCH}" == "arm64"
  ${IfNot} ${IsNativeARM64}
    MessageBox MB_ICONSTOP|MB_OK "This installer is for ARM64 Windows. Use the x64 or x86 installer."
    Abort
  ${EndIf}
  SetRegView 64
!endif
FunctionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\WithCrypt\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\withcrypt.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\withcrypt-gui.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다."
FunctionEnd

Function un.onInit
!if "${ARCH}" != "x86"
  SetRegView 64
!endif
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  DetailPrint "Unregistering shell extension ..."
  nsExec::ExecToLog "$INSTDIR\withcrypt-setup.exe unregister"
    
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\WithCrypt.Shell.msix"
  Delete "$INSTDIR\withcrypt_shell.dll"
  Delete "$INSTDIR\withcrypt-setup.exe"
  Delete "$INSTDIR\withcrypt-gui.exe"
  Delete "$INSTDIR\ShellIcon.ico"
  Delete "$INSTDIR\withcrypt.exe"

  Delete "$SMPROGRAMS\WithCrypt\Uninstall.lnk"
  Delete "$SMPROGRAMS\WithCrypt\Website.lnk"
  Delete "$DESKTOP\WithCrypt.lnk"
  Delete "$SMPROGRAMS\WithCrypt\WithCrypt.lnk"

  RMDir "$SMPROGRAMS\WithCrypt"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd